namespace BatteryTray;

internal static partial class I18n
{
    private static readonly string[] Turkish =
    [
        "TabbyBBMonitor",
        "Bluetooth pil bilgileri alınamadı",
        "Bluetooth cihazları listelenemedi.",
        "düştü",
        "düzeldi",
        "{0} pil durumu: {1}",
        "{0}% — {1} durumundan {2} durumuna değişti.",
        "Alma hatası",
        "Bluetooth cihazı bulunamadı",
        "Pil seviyesi bilinmiyor",
        "Şimdi denetle",
        "Ayarlar...",
        "Çıkış",
        "Kritik",
        "Düşük",
        "Dikkat",
        "İyi",
        "Bilinmiyor",
        "Eşik aşıldığında bildir",
        "İzle",
        "Cihaz",
        "Pil",
        "Durum",
        "İzlenen cihazları, pil eşiklerini ve bildirimleri yapılandırın.",
        "Kaydet",
        "İptal",
        "Cihazlar",
        "Cihaz ara",
        "Kullanılamayanları göster",
        "Yeniden algıla",
        "Bir cihaz seçin",
        "Bu cihazı izle",
        "Varsayılanlara sıfırla",
        "Bu eşikleri tümüne uygula",
        "Bu cihaz ayarını sil",
        "Kritik (veya altı)",
        "Düşük (veya altı)",
        "Dikkat (veya altı)",
        "Bildirim eşikleri",
        "Kritik < Düşük < Dikkat sırasıyla ayarlayın. Dikkat üzerindeki seviyeler İyidir.",
        "Genel",
        "İzleme",
        "Denetleme aralığı",
        "saniye (10–3600)",
        "Bildirimler",
        "Yeni cihazlar için varsayılan eşikler",
        "% veya altı",
        "Bu değerler ilk kez algılanan cihazlara uygulanır. Mevcut cihazları Cihazlar sekmesinden değiştirin.",
        "Kullanılamıyor",
        "{0} / {1} cihaz",
        "Şu anda kullanılamıyor",
        "Pil %{0} · {1}",
        "Pil seviyesi alınamadı",
        "Algılanıyor...",
        "Cihazlar algılanamadı",
        "“{0}” ayarları silinsin mi?\nTekrar algılanırsa cihaz varsayılan ayarlarla eklenecektir.",
        "Kullanılamayan cihaz ayarlarını sil",
        "Eşikler {0} cihaza uygulandı.",
        "Tümüne uygula",
        "Yeni cihazlar için varsayılan eşikler geçersiz.",
        "“{0}” eşikleri geçersiz.",
        "Eşikler geçersiz.",
        "Kritik < Düşük < Dikkat sırasıyla ayarlayın.",
        "Ayar hatası"
    ];
}
