namespace BatteryTray;

internal static partial class I18n
{
    private static readonly string[] Polish =
    [
        "TabbyBBMonitor",
        "Nie można pobrać informacji o baterii Bluetooth",
        "Nie można wyliczyć urządzeń Bluetooth.",
        "spadł",
        "przywrócony",
        "Stan baterii urządzenia {0}: {1}",
        "{0}% — Zmiana z {1} na {2}.",
        "Błąd pobierania",
        "Nie znaleziono urządzeń Bluetooth",
        "Poziom baterii jest nieznany",
        "Sprawdź teraz",
        "Ustawienia...",
        "Zakończ",
        "Krytyczny",
        "Niski",
        "Ostrzeżenie",
        "Dobry",
        "Nieznany",
        "Powiadamiaj po przekroczeniu progu",
        "Monitoruj",
        "Urządzenie",
        "Bateria",
        "Stan",
        "Skonfiguruj monitorowane urządzenia, progi baterii i powiadomienia.",
        "Zapisz",
        "Anuluj",
        "Urządzenia",
        "Szukaj urządzeń",
        "Pokaż niedostępne",
        "Wykryj ponownie",
        "Wybierz urządzenie",
        "Monitoruj to urządzenie",
        "Przywróć domyślne",
        "Zastosuj te progi do wszystkich",
        "Usuń ustawienia tego urządzenia",
        "Krytyczny (lub mniej)",
        "Niski (lub mniej)",
        "Ostrzeżenie (lub mniej)",
        "Progi powiadomień",
        "Ustaw w kolejności Krytyczny < Niski < Ostrzeżenie. Poziomy powyżej Ostrzeżenia są Dobre.",
        "Ogólne",
        "Monitorowanie",
        "Interwał sprawdzania",
        "sekund (10–3600)",
        "Powiadomienia",
        "Domyślne progi dla nowych urządzeń",
        "% lub mniej",
        "Te wartości dotyczą urządzeń wykrytych po raz pierwszy. Istniejące urządzenia można zmienić na karcie Urządzenia.",
        "Niedostępne",
        "{0} / {1} urządzeń",
        "Obecnie niedostępne",
        "Bateria {0}% · {1}",
        "Nie można pobrać poziomu baterii",
        "Wykrywanie...",
        "Nie można wykryć urządzeń",
        "Usunąć ustawienia urządzenia „{0}”?\nPo ponownym wykryciu urządzenie zostanie dodane z ustawieniami domyślnymi.",
        "Usuń ustawienia niedostępnego urządzenia",
        "Zastosowano progi do {0} urządzeń.",
        "Zastosuj do wszystkich",
        "Domyślne progi dla nowych urządzeń są nieprawidłowe.",
        "Progi urządzenia „{0}” są nieprawidłowe.",
        "Progi są nieprawidłowe.",
        "Ustaw je w kolejności Krytyczny < Niski < Ostrzeżenie.",
        "Błąd ustawień"
    ];
}
