namespace BatteryTray;

internal static partial class I18n
{
    private static readonly string[] Vietnamese =
    [
        "TabbyBBMonitor",
        "Không thể lấy thông tin pin Bluetooth",
        "Không thể liệt kê các thiết bị Bluetooth.",
        "giảm",
        "phục hồi",
        "Trạng thái pin của {0}: {1}",
        "{0}% — Đã chuyển từ {1} sang {2}.",
        "Lỗi truy xuất",
        "Không tìm thấy thiết bị Bluetooth",
        "Không xác định mức pin",
        "Kiểm tra ngay",
        "Cài đặt...",
        "Thoát",
        "Nghiêm trọng",
        "Thấp",
        "Cảnh báo",
        "Tốt",
        "Không xác định",
        "Thông báo khi vượt qua ngưỡng",
        "Giám sát",
        "Thiết bị",
        "Pin",
        "Trạng thái",
        "Cấu hình thiết bị được giám sát, ngưỡng pin và thông báo.",
        "Lưu",
        "Hủy",
        "Thiết bị",
        "Tìm thiết bị",
        "Hiện thiết bị không khả dụng",
        "Phát hiện lại",
        "Chọn một thiết bị",
        "Giám sát thiết bị này",
        "Đặt lại mặc định",
        "Áp dụng các ngưỡng này cho tất cả",
        "Xóa cài đặt của thiết bị này",
        "Nghiêm trọng (bằng hoặc thấp hơn)",
        "Thấp (bằng hoặc thấp hơn)",
        "Cảnh báo (bằng hoặc thấp hơn)",
        "Ngưỡng thông báo",
        "Đặt theo thứ tự Nghiêm trọng < Thấp < Cảnh báo. Mức cao hơn Cảnh báo được xem là Tốt.",
        "Chung",
        "Giám sát",
        "Khoảng kiểm tra",
        "giây (10–3600)",
        "Thông báo",
        "Ngưỡng mặc định cho thiết bị mới",
        "% hoặc thấp hơn",
        "Các giá trị này áp dụng cho thiết bị được phát hiện lần đầu. Thay đổi thiết bị hiện có trong thẻ Thiết bị.",
        "Không khả dụng",
        "{0} / {1} thiết bị",
        "Hiện không khả dụng",
        "Pin {0}% · {1}",
        "Không thể lấy mức pin",
        "Đang phát hiện...",
        "Không thể phát hiện thiết bị",
        "Xóa cài đặt của “{0}”?\nNếu được phát hiện lại, thiết bị sẽ được thêm với cài đặt mặc định.",
        "Xóa cài đặt thiết bị không khả dụng",
        "Đã áp dụng ngưỡng cho {0} thiết bị.",
        "Áp dụng cho tất cả",
        "Ngưỡng mặc định cho thiết bị mới không hợp lệ.",
        "Ngưỡng của “{0}” không hợp lệ.",
        "Các ngưỡng không hợp lệ.",
        "Đặt theo thứ tự Nghiêm trọng < Thấp < Cảnh báo.",
        "Lỗi cài đặt"
    ];
}
