namespace BatteryTray;

internal static partial class I18n
{
    private static readonly string[] Spanish =
    [
        "TabbyBBMonitor",
        "No se pudo obtener la información de la batería Bluetooth",
        "No se pudieron enumerar los dispositivos Bluetooth.",
        "bajó",
        "se recuperó",
        "Estado de la batería de {0}: {1}",
        "{0}% — Cambió de {1} a {2}.",
        "Error de obtención",
        "No se encontraron dispositivos Bluetooth",
        "Nivel de batería desconocido",
        "Comprobar ahora",
        "Configuración...",
        "Salir",
        "Crítico",
        "Bajo",
        "Precaución",
        "Bueno",
        "Desconocido",
        "Notificar al cruzar un umbral",
        "Supervisar",
        "Dispositivo",
        "Batería",
        "Estado",
        "Configura los dispositivos supervisados, los umbrales de batería y las notificaciones.",
        "Guardar",
        "Cancelar",
        "Dispositivos",
        "Buscar dispositivos",
        "Mostrar no disponibles",
        "Volver a detectar",
        "Selecciona un dispositivo",
        "Supervisar este dispositivo",
        "Restablecer valores",
        "Aplicar estos umbrales a todos",
        "Eliminar la configuración de este dispositivo",
        "Crítico (igual o inferior)",
        "Bajo (igual o inferior)",
        "Precaución (igual o inferior)",
        "Umbrales de notificación",
        "Establece el orden Crítico < Bajo < Precaución. Los niveles superiores a Precaución son Buenos.",
        "General",
        "Supervisión",
        "Intervalo de comprobación",
        "segundos (10–3600)",
        "Notificaciones",
        "Umbrales predeterminados para dispositivos nuevos",
        "% o menos",
        "Estos valores se aplican a los dispositivos detectados por primera vez. Cambia los existentes en la pestaña Dispositivos.",
        "No disponible",
        "{0} / {1} dispositivos",
        "No disponible actualmente",
        "Batería {0}% · {1}",
        "No se pudo obtener el nivel de batería",
        "Detectando...",
        "No se pudieron detectar dispositivos",
        "¿Eliminar la configuración de “{0}”?\nSi vuelve a detectarse, el dispositivo se añadirá con la configuración predeterminada.",
        "Eliminar configuración del dispositivo no disponible",
        "Se aplicaron los umbrales a {0} dispositivos.",
        "Aplicar a todos",
        "Los umbrales predeterminados para dispositivos nuevos no son válidos.",
        "Los umbrales de “{0}” no son válidos.",
        "Los umbrales no son válidos.",
        "Establécelos en el orden Crítico < Bajo < Precaución.",
        "Error de configuración"
    ];
}
