namespace BatteryTray;

internal static partial class I18n
{
    private static readonly string[] Portuguese =
    [
        "TabbyBBMonitor",
        "Não foi possível obter as informações da bateria Bluetooth",
        "Não foi possível enumerar os dispositivos Bluetooth.",
        "diminuiu",
        "recuperou",
        "Estado da bateria de {0}: {1}",
        "{0}% — Mudou de {1} para {2}.",
        "Erro de obtenção",
        "Nenhum dispositivo Bluetooth encontrado",
        "Nível da bateria desconhecido",
        "Verificar agora",
        "Definições...",
        "Sair",
        "Crítico",
        "Baixo",
        "Atenção",
        "Bom",
        "Desconhecido",
        "Notificar ao cruzar um limite",
        "Monitorizar",
        "Dispositivo",
        "Bateria",
        "Estado",
        "Configure os dispositivos monitorizados, os limites da bateria e as notificações.",
        "Guardar",
        "Cancelar",
        "Dispositivos",
        "Pesquisar dispositivos",
        "Mostrar indisponíveis",
        "Detetar novamente",
        "Selecione um dispositivo",
        "Monitorizar este dispositivo",
        "Repor predefinições",
        "Aplicar estes limites a todos",
        "Eliminar as definições deste dispositivo",
        "Crítico (igual ou inferior)",
        "Baixo (igual ou inferior)",
        "Atenção (igual ou inferior)",
        "Limites de notificação",
        "Defina pela ordem Crítico < Baixo < Atenção. Os níveis acima de Atenção são Bons.",
        "Geral",
        "Monitorização",
        "Intervalo de verificação",
        "segundos (10–3600)",
        "Notificações",
        "Limites predefinidos para novos dispositivos",
        "% ou menos",
        "Estes valores aplicam-se a dispositivos detetados pela primeira vez. Altere os existentes no separador Dispositivos.",
        "Indisponível",
        "{0} / {1} dispositivos",
        "Atualmente indisponível",
        "Bateria {0}% · {1}",
        "Não foi possível obter o nível da bateria",
        "A detetar...",
        "Não foi possível detetar dispositivos",
        "Eliminar as definições de “{0}”?\nSe for detetado novamente, o dispositivo será adicionado com as predefinições.",
        "Eliminar definições do dispositivo indisponível",
        "Limites aplicados a {0} dispositivos.",
        "Aplicar a todos",
        "Os limites predefinidos para novos dispositivos não são válidos.",
        "Os limites de “{0}” não são válidos.",
        "Os limites não são válidos.",
        "Defina-os pela ordem Crítico < Baixo < Atenção.",
        "Erro de definições"
    ];
}
