namespace BatteryTray;

internal static partial class I18n
{
    private static readonly string[] French =
    [
        "TabbyBBMonitor",
        "Impossible de récupérer les informations de batterie Bluetooth",
        "Impossible de répertorier les appareils Bluetooth.",
        "a baissé",
        "a été rétabli",
        "État de la batterie de {0} : {1}",
        "{0} % — Passage de {1} à {2}.",
        "Erreur de récupération",
        "Aucun appareil Bluetooth trouvé",
        "Niveau de batterie inconnu",
        "Vérifier maintenant",
        "Paramètres...",
        "Quitter",
        "Critique",
        "Faible",
        "Attention",
        "Bon",
        "Inconnu",
        "Notifier lors du franchissement de seuil",
        "Surveiller",
        "Appareil",
        "Batterie",
        "État",
        "Configurez les appareils surveillés, les seuils de batterie et les notifications.",
        "Enregistrer",
        "Annuler",
        "Appareils",
        "Rechercher des appareils",
        "Afficher les indisponibles",
        "Redétecter",
        "Sélectionnez un appareil",
        "Surveiller cet appareil",
        "Rétablir les valeurs par défaut",
        "Appliquer ces seuils à tous",
        "Supprimer les paramètres de cet appareil",
        "Critique (au plus)",
        "Faible (au plus)",
        "Attention (au plus)",
        "Seuils de notification",
        "Définissez les seuils dans cet ordre : Critique < Faible < Attention. Les niveaux supérieurs à Attention sont Bons.",
        "Général",
        "Surveillance",
        "Intervalle de vérification",
        "secondes (10–3600)",
        "Notifications",
        "Seuils par défaut des nouveaux appareils",
        "% ou moins",
        "Ces valeurs concernent les appareils détectés pour la première fois. Modifiez les appareils existants dans la section Appareils.",
        "Indisponible",
        "{0} / {1} appareils",
        "Actuellement indisponible",
        "Batterie {0} % · {1}",
        "Impossible de récupérer le niveau de batterie",
        "Détection...",
        "Impossible de détecter les appareils",
        "Supprimer les paramètres de « {0} » ?\nSi cet appareil est à nouveau détecté, il sera ajouté avec les paramètres par défaut.",
        "Supprimer les paramètres du périphérique indisponible",
        "Seuils appliqués à {0} appareils.",
        "Appliquer à tous",
        "Les seuils par défaut des nouveaux appareils ne sont pas valides.",
        "Les seuils de « {0} » ne sont pas valides.",
        "Les seuils ne sont pas valides.",
        "Définissez-les dans cet ordre : Critique < Faible < Attention.",
        "Erreur de paramètres"
    ];
}
