namespace BatteryTray;

internal static partial class I18n
{
    private static readonly string[] English =
    [
        "TabbyBBMonitor",
        "Could not retrieve Bluetooth battery information",
        "Failed to enumerate Bluetooth devices.",
        "decreased",
        "recovered",
        "{0} battery status {1}",
        "{0}% — Changed from {1} to {2}.",
        "Retrieval error",
        "No Bluetooth devices found",
        "Battery level unknown",
        "Check now",
        "Settings...",
        "Exit",
        "Critical",
        "Low",
        "Caution",
        "Good",
        "Unknown",
        "Notify when a threshold is crossed",
        "Monitor",
        "Device",
        "Battery",
        "Status",
        "Configure monitored devices, battery thresholds, and notifications.",
        "Save",
        "Cancel",
        "Devices",
        "Search devices",
        "Show unavailable",
        "Rediscover",
        "Select a device",
        "Monitor this device",
        "Reset to defaults",
        "Apply these thresholds to all",
        "Delete this device setting",
        "Critical (at or below)",
        "Low (at or below)",
        "Caution (at or below)",
        "Notification thresholds",
        "Set in the order Critical < Low < Caution. Levels above Caution are Good.",
        "General",
        "Monitoring",
        "Check interval",
        "seconds (10–3600)",
        "Notifications",
        "Default thresholds for new devices",
        "% or below",
        "These values apply to devices detected for the first time. Change existing devices on the Devices tab.",
        "Unavailable",
        "{0} / {1} devices",
        "Currently unavailable",
        "Battery {0}% · {1}",
        "Battery level could not be retrieved",
        "Discovering...",
        "Could not discover devices",
        "Delete the settings for “{0}”?\nIf detected again, the device will be added with the default settings.",
        "Delete unavailable device settings",
        "Applied thresholds to {0} devices.",
        "Apply to all",
        "The default thresholds for new devices are invalid.",
        "The thresholds for “{0}” are invalid.",
        "The thresholds are invalid.",
        "Set them in the order Critical < Low < Caution.",
        "Settings error"
    ];

    private static readonly string[] Japanese =
    [
        "TabbyBBMonitor",
        "Bluetooth 電池情報を取得できません",
        "Bluetooth デバイスの列挙に失敗しました。",
        "低下",
        "回復",
        "{0} の電池状態が{1}",
        "{0}% — {1} から {2} に変わりました。",
        "取得エラー",
        "Bluetooth デバイスが見つかりません",
        "残量不明",
        "今すぐ確認",
        "設定...",
        "終了",
        "危険",
        "低下",
        "注意",
        "良好",
        "不明",
        "閾値をまたいだときに通知する",
        "監視",
        "デバイス",
        "残量",
        "状態",
        "監視するデバイス、電池残量の閾値、通知方法を設定します。",
        "保存",
        "キャンセル",
        "デバイス",
        "デバイス名を検索",
        "未検出を表示",
        "再検出",
        "デバイスを選択",
        "このデバイスを監視する",
        "初期値に戻す",
        "この閾値をすべてに適用",
        "このデバイスの設定を削除",
        "危険（以下）",
        "低下（以下）",
        "注意（以下）",
        "通知の閾値",
        "危険 < 低下 < 注意 の順で指定します。注意より大きい残量は「良好」です。",
        "全般",
        "監視",
        "確認間隔",
        "秒（10～3600）",
        "通知",
        "新しいデバイスの初期閾値",
        "% 以下",
        "ここで指定した値は、今後初めて検出されるデバイスに適用されます。既存デバイスは「デバイス」タブから変更できます。",
        "未検出",
        "{0} / {1} 台",
        "現在は検出されていません",
        "残量 {0}%・{1}",
        "残量情報を取得できません",
        "検出中...",
        "デバイスを検出できません",
        "「{0}」の設定を削除しますか？\n再検出された場合は、初期設定で追加されます。",
        "未検出デバイスの設定を削除",
        "{0} 台に閾値を適用しました。",
        "一括適用",
        "新しいデバイスの初期閾値が正しくありません。",
        "「{0}」の閾値が正しくありません。",
        "閾値が正しくありません。",
        "危険 < 低下 < 注意 の順に設定してください。",
        "設定エラー"
    ];
}
