namespace BatteryTray;

internal static partial class I18n
{
    private static readonly string[] German =
    [
        "TabbyBBMonitor",
        "Bluetooth-Akkuinformationen konnten nicht abgerufen werden",
        "Bluetooth-Geräte konnten nicht aufgelistet werden.",
        "gesunken",
        "erholt",
        "Akkustatus von {0}: {1}",
        "{0}% — Von {1} zu {2} gewechselt.",
        "Abruffehler",
        "Keine Bluetooth-Geräte gefunden",
        "Akkustand unbekannt",
        "Jetzt prüfen",
        "Einstellungen...",
        "Beenden",
        "Kritisch",
        "Niedrig",
        "Warnung",
        "Gut",
        "Unbekannt",
        "Beim Überschreiten eines Schwellenwerts benachrichtigen",
        "Überwachen",
        "Gerät",
        "Akku",
        "Status",
        "Überwachte Geräte, Akkuschwellenwerte und Benachrichtigungen konfigurieren.",
        "Speichern",
        "Abbrechen",
        "Geräte",
        "Geräte suchen",
        "Nicht verfügbare anzeigen",
        "Neu erkennen",
        "Gerät auswählen",
        "Dieses Gerät überwachen",
        "Auf Standardwerte zurücksetzen",
        "Diese Schwellenwerte auf alle anwenden",
        "Einstellungen dieses Geräts löschen",
        "Kritisch (höchstens)",
        "Niedrig (höchstens)",
        "Warnung (höchstens)",
        "Benachrichtigungsschwellenwerte",
        "In der Reihenfolge Kritisch < Niedrig < Warnung festlegen. Werte über Warnung gelten als Gut.",
        "Allgemein",
        "Überwachung",
        "Prüfintervall",
        "Sekunden (10–3600)",
        "Benachrichtigungen",
        "Standardschwellenwerte für neue Geräte",
        "% oder weniger",
        "Diese Werte gelten für erstmals erkannte Geräte. Vorhandene Geräte können auf der Registerkarte Geräte geändert werden.",
        "Nicht verfügbar",
        "{0} / {1} Geräte",
        "Derzeit nicht verfügbar",
        "Akku {0}% · {1}",
        "Akkustand konnte nicht abgerufen werden",
        "Erkennung läuft...",
        "Geräte konnten nicht erkannt werden",
        "Einstellungen für „{0}“ löschen?\nBei erneuter Erkennung wird das Gerät mit den Standardeinstellungen hinzugefügt.",
        "Einstellungen des nicht verfügbaren Geräts löschen",
        "Schwellenwerte auf {0} Geräte angewendet.",
        "Auf alle anwenden",
        "Die Standardschwellenwerte für neue Geräte sind ungültig.",
        "Die Schwellenwerte für „{0}“ sind ungültig.",
        "Die Schwellenwerte sind ungültig.",
        "In der Reihenfolge Kritisch < Niedrig < Warnung festlegen.",
        "Einstellungsfehler"
    ];
}
