namespace BatteryTray;

internal static partial class I18n
{
    private static readonly string[] Italian =
    [
        "TabbyBBMonitor",
        "Impossibile recuperare le informazioni sulla batteria Bluetooth",
        "Impossibile enumerare i dispositivi Bluetooth.",
        "diminuito",
        "ripristinato",
        "Stato della batteria di {0}: {1}",
        "{0}% — Passato da {1} a {2}.",
        "Errore di recupero",
        "Nessun dispositivo Bluetooth trovato",
        "Livello batteria sconosciuto",
        "Controlla ora",
        "Impostazioni...",
        "Esci",
        "Critico",
        "Basso",
        "Attenzione",
        "Buono",
        "Sconosciuto",
        "Notifica quando viene superata una soglia",
        "Monitora",
        "Dispositivo",
        "Batteria",
        "Stato",
        "Configura i dispositivi monitorati, le soglie della batteria e le notifiche.",
        "Salva",
        "Annulla",
        "Dispositivi",
        "Cerca dispositivi",
        "Mostra non disponibili",
        "Rileva di nuovo",
        "Seleziona un dispositivo",
        "Monitora questo dispositivo",
        "Ripristina predefiniti",
        "Applica queste soglie a tutti",
        "Elimina le impostazioni di questo dispositivo",
        "Critico (massimo)",
        "Basso (massimo)",
        "Attenzione (massimo)",
        "Soglie di notifica",
        "Imposta in ordine Critico < Basso < Attenzione. I livelli superiori ad Attenzione sono Buoni.",
        "Generale",
        "Monitoraggio",
        "Intervallo di controllo",
        "secondi (10–3600)",
        "Notifiche",
        "Soglie predefinite per i nuovi dispositivi",
        "% o meno",
        "Questi valori si applicano ai dispositivi rilevati per la prima volta. Modifica quelli esistenti nella scheda Dispositivi.",
        "Non disponibile",
        "{0} / {1} dispositivi",
        "Attualmente non disponibile",
        "Batteria {0}% · {1}",
        "Impossibile recuperare il livello della batteria",
        "Rilevamento...",
        "Impossibile rilevare i dispositivi",
        "Eliminare le impostazioni di “{0}”?\nSe rilevato di nuovo, il dispositivo verrà aggiunto con le impostazioni predefinite.",
        "Elimina impostazioni dispositivo non disponibile",
        "Soglie applicate a {0} dispositivi.",
        "Applica a tutti",
        "Le soglie predefinite per i nuovi dispositivi non sono valide.",
        "Le soglie di “{0}” non sono valide.",
        "Le soglie non sono valide.",
        "Impostale in ordine Critico < Basso < Attenzione.",
        "Errore nelle impostazioni"
    ];
}
