namespace BatteryTray;

internal static partial class I18n
{
    private static readonly string[] Indonesian =
    [
        "TabbyBBMonitor",
        "Tidak dapat mengambil informasi baterai Bluetooth",
        "Gagal mencantumkan perangkat Bluetooth.",
        "menurun",
        "pulih",
        "Status baterai {0}: {1}",
        "{0}% — Berubah dari {1} menjadi {2}.",
        "Kesalahan pengambilan",
        "Tidak ada perangkat Bluetooth yang ditemukan",
        "Tingkat baterai tidak diketahui",
        "Periksa sekarang",
        "Pengaturan...",
        "Keluar",
        "Kritis",
        "Rendah",
        "Waspada",
        "Baik",
        "Tidak diketahui",
        "Beri tahu saat ambang terlewati",
        "Pantau",
        "Perangkat",
        "Baterai",
        "Status",
        "Atur perangkat yang dipantau, ambang baterai, dan notifikasi.",
        "Simpan",
        "Batal",
        "Perangkat",
        "Cari perangkat",
        "Tampilkan yang tidak tersedia",
        "Deteksi ulang",
        "Pilih perangkat",
        "Pantau perangkat ini",
        "Atur ulang ke default",
        "Terapkan ambang ini ke semua",
        "Hapus pengaturan perangkat ini",
        "Kritis (atau kurang)",
        "Rendah (atau kurang)",
        "Waspada (atau kurang)",
        "Ambang notifikasi",
        "Atur dengan urutan Kritis < Rendah < Waspada. Tingkat di atas Waspada dianggap Baik.",
        "Umum",
        "Pemantauan",
        "Interval pemeriksaan",
        "detik (10–3600)",
        "Notifikasi",
        "Ambang default untuk perangkat baru",
        "% atau kurang",
        "Nilai ini berlaku untuk perangkat yang terdeteksi pertama kali. Ubah perangkat yang ada pada tab Perangkat.",
        "Tidak tersedia",
        "{0} / {1} perangkat",
        "Saat ini tidak tersedia",
        "Baterai {0}% · {1}",
        "Tingkat baterai tidak dapat diambil",
        "Mendeteksi...",
        "Perangkat tidak dapat dideteksi",
        "Hapus pengaturan untuk “{0}”?\nJika terdeteksi lagi, perangkat akan ditambahkan dengan pengaturan default.",
        "Hapus pengaturan perangkat yang tidak tersedia",
        "Ambang diterapkan ke {0} perangkat.",
        "Terapkan ke semua",
        "Ambang default untuk perangkat baru tidak valid.",
        "Ambang untuk “{0}” tidak valid.",
        "Ambang tidak valid.",
        "Atur dengan urutan Kritis < Rendah < Waspada.",
        "Kesalahan pengaturan"
    ];
}
